# Generated by Django 4.1.6 on 2023-03-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refus',
            name='concour',
        ),
        migrations.RemoveField(
            model_name='refus',
            name='etudiant',
        ),
        migrations.DeleteModel(
            name='admis',
        ),
        migrations.DeleteModel(
            name='refus',
        ),
    ]
