# Generated by Django 4.1.7 on 2023-03-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='profile_pic',
            field=models.ImageField(default='student/img/user.png', upload_to='student/img'),
        ),
    ]
