# Generated by Django 4.1.6 on 2023-02-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='confirmpassword',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='password',
            field=models.CharField(blank=True, default=True, max_length=50, null=True),
        ),
    ]
