# Generated by Django 4.1.6 on 2023-03-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
