# Generated by Django 4.1.6 on 2023-02-26 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_etudiant_confirmpassword_alter_etudiant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cne',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='confirmpassword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
