# Generated by Django 4.1.7 on 2023-03-21 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_etudiant_profile_pic'),
        ('student', '0002_remove_refus_concour_remove_refus_etudiant_and_more'),
    ]

    operations = [
    ]
