# Generated by Django 4.1.6 on 2023-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_etudiant_user_alter_etudiant_cne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='username',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
