# Generated by Django 4.1.6 on 2023-02-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_etudiant_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='username',
        ),
    ]
